# Generated by Django 2.2 on 2019-04-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190417_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicture',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='users.User'),
        ),
    ]
