# Generated by Django 2.2 on 2019-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190417_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='md5_chars',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='md5_chars'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='md5_digit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='md5_digit'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='sha1_chars',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sha1_chars'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='sha1_digit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sha1_digit'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='sha256_chars',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sha256_chars'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='sha256_digit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sha256_digit'),
        ),
    ]
